version: "3"
services:
  web:
    image: siemensapp
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8085"
    networks:
      - webnet
networks:
  webnet: