version: '3'
services:
  web:
    image: 'tomcat'
    ports:
      - '8080:8080'
    depends_on: ['nginx']
  nginx:
    image: 'nginx'
    ports:
      - '80:80'
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
